create table city (
    id bigint generated by default as identity,
    state_id bigint,
    name varchar(80),
    primary key (id)
);
create table group_permissions_tb (
    group_id bigint not null,
    permission_id bigint not null
);
create table group_permissions (
    id bigint generated by default as identity,
    name varchar(80),
    primary key (id)
);
create table kitchen (
    id bigint generated by default as identity,
    name varchar(80),
    primary key (id)
);

create table payment_type (
    id bigint generated by default as identity,
    description varchar(200),
    primary key (id)
);

create table permission (
    id bigint generated by default as identity,
    description varchar(200),
    name varchar(80),
    primary key (id)
);

create table product (
    active boolean not null,
    price numeric(38,2),
    id bigint generated by default as identity,
    restaurant_id bigint,
    description varchar(200),
    name varchar(80),
    primary key (id)
);

create table restaurant (
    delivery_tax numeric(38,2),
    address_city bigint,
    created_at datetime,
    id bigint generated by default as identity,
    kitchen_id bigint,
    updated_at datetime,
    address_complement varchar(80),
    address_district varchar(80),
    address_number varchar(10),
    address_public_place varchar(80),
    address_zip_code varchar(80),
    name varchar(80), primary key (id)
);

create table restaurant_payment_type (
    payment_type_id bigint not null,
    restaurant_id bigint not null
);
create table restaurant_products (
    products_id bigint not null unique,
    restaurant_id bigint not null
 );
create table state (
    id bigint generated by default as identity,
    name varchar(80),
    primary key (id)
);
create table user_group_tb (
    group_id bigint not null,
    user_id bigint not null
);
create table user_client (
    created_at timestamp(6),
    id bigint generated by default as identity,
    email varchar(80) unique,
    name varchar(80),
    password varchar(255),
    primary key (id)
);